services:

  postgres:
    image: postgres:18
    ports: [ "5432:5432" ]

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports: [ "8081:8080" ]

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    volumes:
      - keycloak_data:/opt/keycloak/data

  kafka:
    image: apache/kafka:4.3.1
    ports: [ "9092:9092" ]

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test: [ "CMD-SHELL",
              "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 15


  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports: [ "8085:8080" ]

    environment:
      KAFKA_CLUSTERS_0_NAME: checkdev-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    depends_on:
      kafka:
        condition: service_healthy

  eureka:
    build: ../checkdev-eureka
    ports: [ "9009:9009" ]

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9009 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10

  auth:
    build: ../checkdev-auth
    ports: [ "9900:9900" ]

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cd_auth
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/checkdev/protocol/openid-connect/certs

    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

  desc:
    build: ../checkdev-desc
    ports: [ "9902:9902" ]

    environment:
      SECURITY_OAUTH2_RESOURCE_USERINFOURI: http://auth:9900/user
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cd_desc
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka

  generator:
    build: ../checkdev-generator
    ports: [ "9903:9903" ]

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cd_generator
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SECURITY_OAUTH2_RESOURCE_USERINFOURI: http://auth:9900/user
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka
      HH_TOKEN: ${HH_TOKEN}

  mock:
    build: ../checkdev-mock
    ports: [ "9912:9912" ]

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cd_mock
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SECURITY_OAUTH2_RESOURCE_USERINFOURI: http://auth:9900/user
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka


  site:
    build: ../checkdev-site
    ports: [ "8080:8080" ]

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092

    depends_on:
      kafka:
        condition: service_healthy
      eureka:
        condition: service_healthy
      auth:
        condition: service_started
      desc:
        condition: service_started
      generator:
        condition: service_started
      mock:
        condition: service_started

    entrypoint: [ "sh", "-c", "sleep 25 && exec java -jar app.jar" ]

  notification:
    build: ../checkdev-notification
    ports: [ "9920:9920" ]

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cd_notification
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:29092

      SECURITY_OAUTH2_RESOURCE_USERINFOURI: http://auth:9900/user
      SERVER_AUTH: http://auth:9900
      SITE_LOGIN_URL: http://site:8080/login

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:9009/eureka
      TG_USERNAME: ${TG_USERNAME}

      TG_TOKEN: ${TG_TOKEN}
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/checkdev/protocol/openid-connect/token
      KEYCLOAK_CLIENT_ID: notification
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      eureka:
        condition: service_healthy
      auth:
        condition: service_started

volumes:
  postgres_data:
  keycloak_data:
  kafka_data:
